version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:6.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms300m -Xmx300m"
      discovery.type: "single-node"
    volumes:
      - es-data:/usr/share/elasticsearch/data
  fluentd:
    build: .
    ports:
      - "8080:8080"
      - "24224:24224"
  front:
    image: nginx:1.16.0

  kibana:
    image: kibana:6.4.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  elastalert:
    image: 'servercentral/elastalert'
    ports:
      - '3030:3030'
      - '3333:3333'
    volumes:
      - ./elastalert.yaml:/opt/elastalert/config.yaml
      - ./api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates

  praeco:
    image: 'servercentral/praeco'
    ports:
      - '8088:8080'
    volumes:
      - ./praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  es-data:
    driver: local
